### ISSUE TITLE
improve message

### ISSUE THREAD

**Issue by al-niessner** [aria-jpl/coseismic_enumerator#1]
From current run, the lack of an orbit file showed up and was handled correctly with this message:

```
Traceback (most recent call last):
  File "/home/ops/verdi/ops/coseismic_enumerator/iterate.py", line 53, in main
    try: active.process (aoi)
  File "/home/ops/verdi/ops/coseismic_enumerator/active.py", line 109, in process
    eofs = [orbit.fetch (acq) for acq in acqs]
  File "/home/ops/verdi/ops/coseismic_enumerator/active.py", line 109, in <listcomp>
    eofs = [orbit.fetch (acq) for acq in acqs]
  File "/home/ops/verdi/ops/coseismic_enumerator/orbit.py", line 62, in fetch
    if not orb and not any(mat): raise NoOrbitsAvailable(acquisition['id'])
orbit.NoOrbitsAvailable: acquisition-S1B_IW_SLC__1SDV_20210302T095524_20210302T095552_025834_0314C2_AAA5-esa_scihub
```

However, which AOI was this for?

**Comment by riverma** [comment]
Hi @al-niessner - I submitted this job via your `crontab` script, i.e. https://github.com/aria-jpl/coseismic_enumerator/blob/main/submit.py and don't have a clear way to tell you which AOI this was for from the job alone.

Do you have a procedure I could run through to provide you the AOI info?

**Comment by al-niessner** [comment]
This is a  code change, assign it to me please.
